### ISSUE TITLE
Wiki updates to merge: Fusion 360

### ISSUE THREAD

**Issue by thesage1014** [Opentotum/Opentotum#3]
I forked the wiki and improved the documentation for fusion
https://github.com/thesage1014/Opentotum/wiki

Can somebody merge this in, or give me access to the wiki to make the edits?

**Comment by alessiocavalieri** [comment]
Invited

Il giorno sab 27 lug 2019 alle ore 10:58 Servald <notifications@github.com>
ha scritto:
