### ISSUE TITLE
LaserWeb to FABtotum postprocessor

### ISSUE THREAD

**Issue by pisuke** [Opentotum/Opentotum#4]
Hi, I've created this post-processor for the laser head: [lw2fabtotum](https://github.com/pisuke/lw2fabtotum)

Maybe it can be added to the list of postprocessors?
Happy to accept suggestions for new features too.

Ciao!

**Comment by alessiocavalieri** [comment]
Yes sure, i add soon as possible in the Opentotum wiki

Thanks for share.

I use LaserWeb for an other laser (based on GRBL) and i find it very
useful, i think this post processor is a great thing!
( https://itink.it/wiki/doku.php?id=en:tinkering:laser:eleksmakera3pro )




Il giorno sab 9 mag 2020 alle ore 13:03 Francesco Anselmo <
notifications@github.com> ha scritto:

**Comment by pisuke** [comment]
Great, thanks for confirming you will add it to the wiki.
Let me know if it works for you and if you have any suggestions.
I agree LaserWeb is fantastic!
Ciao!

**Comment by alessiocavalieri** [comment]
Added to the wiki here:
https://github.com/Opentotum/Opentotum/wiki/CNC-Post-Processors#lw2fabtotum

and in side menu

after imagescan laser software:

[image: image.png]





Il giorno lun 11 mag 2020 alle ore 23:53 Francesco Anselmo <
notifications@github.com> ha scritto:

**Comment by pisuke** [comment]
Great, thanks! Closing this issue then, ciao!
