### ISSUE TITLE
Bottle at sea, looking for a new carriage ribbon cable! 

### ISSUE THREAD

**Issue by mgcrea** [Opentotum/Opentotum#5]
Hey all!

Not sure if anyone is reading this but I'm looking for a spare part for my original fabtotum printer.

Somehow I broke the ribbon cable from the head carriage to the motor driver board (cable was flaky and broke it trying to fix it!).

Looks like it is glued to the upper part of the carriage so not sure if I can replace only the ribbon.

Anyway if you have a cable / carriage or know where I could find one, I would really appreciate!

Pretty sad to ditch a working printer for a small cable!

![4BA64F4A-435B-4496-863F-01C8CD98D9DB_1_105_c](https://user-images.githubusercontent.com/108273/82593133-4a31b400-9ba2-11ea-8eac-5843cec8c0e2.jpeg)
![D2D510C3-FF73-43A8-B0DE-8CECB8CB4BDB_1_105_c](https://user-images.githubusercontent.com/108273/82593140-4c940e00-9ba2-11ea-9cb7-2a4c6ed8a2b5.jpeg)

Thanks!

**Comment by CryoRig** [comment]
Someone in the facebook user group  made new cables and sells them
I can't post a link as i no longer use fb
I think the group was called fabtotum user group or something alike

**Comment by CryoRig** [comment]
here`s the post
https://www.facebook.com/groups/1052715011528991/permalink/1895629217237562/
